github-repository-dispatcher-service1:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service1-main
    tag: 7de2a4c133a8
github-repository-dispatcher-service2:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service2-main
    tag: 6bdbdffe618b
github-repository-dispatcher-service3:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service3-main
    tag: f510ca5f72b9
github-repository-dispatcher-service4:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service4-main
    tag: 0c73bab1a4bd
