github-repository-dispatcher-service1:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service1-main
    tag: 468b8bca4c8e
github-repository-dispatcher-service2:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service2-main
    tag: ca2059a27c06
github-repository-dispatcher-service3:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service3-main
    tag: 4aff6034529d
github-repository-dispatcher-service4:
  image:
    repository: ghcr.io/atlanhq/github-repository-dispatcher-service4-main
    tag: 73abf9cf5cba
