global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'example-app'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'nginx-app'
    static_configs:
      - targets: ['nginx.example.com:80']

  - job_name: 'example-app-1'
    static_configs:
      - targets: ['localhost:8088']
