name: Test Alert
 
on:
  push:
    branches:
      - main
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Get branch name
        if: startsWith(github.ref, 'refs/heads')
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Exit
        run: |
          exit 1

      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          token: ${{ secrets.MY_PAT }}
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message}: {workflow_url}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          notify_when: "failure"
          mention_users: "U06HFTZDSP9"
          mention_users_when: "failure,warnings"
          # mention_groups: "SAZ94GDB8"
          # mention_groups_when: "failure,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
