name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, phoenix]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - run: echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
        shell: bash

      - name: Get version tag
        run: echo "##[set-output name=version;]$(echo `git ls-remote https://${{ secrets.ORG_PAT_GITHUB }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ steps.get_branch.outputs.branch }} | awk '{ print $1}' | cut -c1-7`)abcd"
        id: get_version

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Harbor Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.HARBOR_URL }}
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}
      #   env:
      #     DOCKER_CLIENT_TIMEOUT: 300
      #     COMPOSE_HTTP_TIMEOUT: 300

      - name: Login to Harbor Registry
        run: |
          bash ./.github/scripts/registry-login.sh "${{ secrets.HARBOR_URL }}" '${{ secrets.HARBOR_USERNAME }}' "${{ secrets.HARBOR_PASSWORD }}"

      - name: Build and push core docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{ github.event.repository.name }}/${{ steps.get_branch.outputs.branch }}:${{ steps.get_version.outputs.version }}
            ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{ github.event.repository.name }}/${{ steps.get_branch.outputs.branch }}:latest
          build-args: |
            ACCESS_TOKEN_USR=$GITHUB_ACTOR
            ACCESS_TOKEN_PWD=${{ secrets.ORG_PAT_GITHUB }}
            SOURCE_BRANCH=${{ steps.get_branch.outputs.branch }}
        env:
          DOCKER_CLIENT_TIMEOUT: 300
          COMPOSE_HTTP_TIMEOUT: 300
