name: Package Docker Image

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get branch name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      id: get_branch

    - run:   echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
      shell: bash

    - name: Get version tag
      run: echo "version=$(echo `git ls-remote https://${{ secrets.MY_PAT }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ steps.get_branch.outputs.branch }} | awk '{ print $1}' | cut -c1-7`)abcd" >> $GITHUB_OUTPUT
      id: get_version

    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Harbor Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_URL }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build -t ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{ steps.get_branch.outputs.branch }}:{{ steps.get_version.outputs.version }} ./App --platform linux/amd64
        docker push ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{ steps.get_branch.outputs.branch }}:{{ steps.get_version.outputs.version }}
