name: Check PR Fields

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_fields:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Run Script to Extract Fields
        run: |
          bash ./.github/scripts/extract_fields.sh "${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        shell: bash

      - name: echo description.txt
        run: |
          cat /tmp/description.txt

      - name: echo jira.txt
        run: |
          cat /tmp/jira.txt

      - name: echo pr_link.txt
        run: |
          cat /tmp/pr_link.txt

      - name: Run Script to Check Fields
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          # Assuming the files are present in the repository
          if [ ! -s "description.txt" ]; then
              echo "description.txt is empty, failing the action..."
              gh pr comment $PR_NUMBER --body "Error: Description field is empty."
              exit 1
          fi
          if [ ! -s "jira.txt" ]; then
              echo "jira.txt is empty, failing the action..."
              gh pr comment $PR_NUMBER --body "Error: Jira Links field is empty."
              exit 1
          fi
          if [ ! -s "pr_link.txt" ]; then
              echo "pr_link.txt is empty, failing the action..."
              gh pr comment $PR_NUMBER --body "Error: PR Links field is empty."
              exit 1
          fi
          echo "All fields are not empty, action can proceed."
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        shell: bash
