name: Check PR Fields

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_fields:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Extract Description
        id: extract_description
        run: |
          description=$(echo "${{ github.event.pull_request.body }}" | awk '/### Description/{flag=1; next} /### Jira Ticket Links/{flag=0} flag' | sed 's/^ *//;s/ *$//')
          echo "description=$description" >> $GITHUB_OUTPUT

      - name: Extract Jira Ticket Link
        id: extract_jira_links
        run: |
          jira=$(echo "${{ github.event.pull_request.body }}" | awk '/### Jira Ticket Links/{flag=1; next} /### PR Links/{flag=0} flag' | sed 's/^ *//;s/ *$//')
          echo "jira_links=$jira_links" >> $GITHUB_OUTPUT

      - name: Extract PR Link
        id: extract_pr_links
        run: |
          pr_link=$(echo "${{ github.event.pull_request.body }}" | awk '/### PR Links/{flag=1; next} /## Type of change/{flag=0} flag' | sed 's/^ *//;s/ *$//')
          echo "pr_link=$pr_link" >> $GITHUB_OUTPUT

      - name: echo description.txt
        run: |
          echo "Description:"
          echo "$PR_DESCRIPTION"
          echo "PR_JIRA:"
          echo "$PR_JIRA"
          echo "PR_PR_LINK:"
          echo "$PR_LINK"
        env:
          PR_DESCRIPTION: ${{ steps.extract_description.outputs.description }}
          PR_JIRA: ${{ steps.extract_jira_links.outputs.jira_links }}
          PR_LINK: ${{ steps.extract_pr_links.outputs.pr_link }}

      # - name: Run Script to Check Fields
      #   run: |
      #     bash ./.github/scripts/check-files.sh "${{ github.event.pull_request.number }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.MY_PAT }}
      #   shell: bash

      - name: Run Python Script to Check Fields
        run: |
          python ./.github/scripts/check-pr-files.py "${{ github.event.pull_request.number }}" "$PR_DESCRIPTION" "$PR_JIRA" "$PR_LINK"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          PR_DESCRIPTION: ${{ steps.extract_description.outputs.description }}
          PR_JIRA: ${{ steps.extract_jira_links.outputs.jira_links }}
          PR_LINK: ${{ steps.extract_pr_links.outputs.pr_link }}
