name: Check PR Fields

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize

jobs:
  check_fields:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.my_pat }}
        fetch-depth: 0

    - name: Store PR Body in a Variable
      id: github_pr_body
      run: |
        {
         echo "GITHUB_PR_BODY<<EOF"
         echo "${{ github.event.pull_request.body }}"
         echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Run Script to Extract Fields
      run: |
        bash ./.github/scripts/extract-fields.sh "${{ steps.github_pr_body.outputs.GITHUB_PR_BODY }}"
      env:
        GH_TOKEN: ${{ secrets.my_pat }}
      shell: bash

    - name: echo description.txt
      run: |
        cat /tmp/description.txt

    - name: echo jira.txt
      run: |
        cat /tmp/jira.txt

    - name: echo pr_link.txt
      run: |
        cat /tmp/pr_link.txt

    - name: Run Python Script to Check Fields
      run: |
        python ./.github/scripts/check-pr-fields.py "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.my_pat }}
