name: Clear Old Releases and Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  clear_old_releases_and_tags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run Cleanup Script
        run: |
          #!/bin/bash

          # Get the current date in YYYY-MM-DD format
          current_date=$(date +"%Y-%m-%d")

          # Find and remove tags older than 30 days
          git tag -l | while read -r tag; do
            tag_date=$(git log -1 --format=%ai "$tag" | cut -d' ' -f1)
            if [[ "$(date -d "$current_date" +%s)" -gt "$(date -d "$tag_date" +%s)" + 2592000 ]]; then
              git tag -d "$tag"
              git push origin ":refs/tags/$tag"
            fi
          done

          # Find and remove releases older than 30 days
          gh release list | while read -r release; do
            release_date=$(gh release view "$release" --json created_at --template "{{.created_at}}" | cut -d' ' -f1)
            if [[ "$(date -d "$current_date" +%s)" -gt "$(date -d "$release_date" +%s)" + 2592000 ]]; then
              gh release delete "$release" --yes
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
