name: Extract PR Fields

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  extract_fields:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Run Script to Extract Fields
        run: |
          bash ./.github/scripts/extract_fields.sh "${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        shell: bash

      - name: Run Script to Post Release Message
        run: |
          python ./.github/scripts/script.py "example-app-1" "$PR_DESCRIPTION" "$PR_JIRA" "$PR_LINK" ${{ secrets.SLACK_WEBHOOK_URL }} "${{ github.event.pull_request.html_url }}"
        env:
          PR_DESCRIPTION: ${{ steps.extract_fields.outputs.description }}
          PR_JIRA: ${{ steps.extract_fields.outputs.jira }}
          PR_LINK: ${{ steps.extract_fields.outputs.pr_link }}
