name: Extract PR Fields

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  extract_fields:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Run Script to Extract Fields
        run: |
          bash ./.github/scripts/extract_fields.sh "${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        shell: bash

      - name: Extract Description
        id: extract_description
        run: |
          description=$(cat /tmp/description.txt)
          echo "description=$description" >> $GITHUB_OUTPUT

      - name: Extract Jira Ticket Link
        id: extract_jira_links
        run: |
          jira=$(cat /tmp/jira.txt)
          echo "jira_links=$jira_links" >> $GITHUB_OUTPUT

      - name: Extract PR Link
        id: extract_pr_links
        run: |
          pr_link=$(cat /tmp/pr_link.txt)
          echo "pr_link=$pr_link" >> $GITHUB_OUTPUT

      - name: Run Script to Post Release Message
        run: |
          python ./.github/scripts/script.py "example-app-1" "$PR_DESCRIPTION" "$PR_JIRA" "$PR_LINK" ${{ secrets.SLACK_WEBHOOK_URL }} "${{ github.event.pull_request.html_url }}"
        env:
          PR_DESCRIPTION: ${{ steps.extract_description.outputs.description }}
          PR_JIRA: ${{ steps.extract_jira_links.outputs.jira_links }}
          PR_LINK: ${{ steps.extract_pr_links.outputs.pr_link }}
