name: Post Release Message on Slack

on:
  pull_request:
    types:
      - closed

jobs:
  extract_fields:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Run Script to Extract Fields
        run: |
          bash ./.github/scripts/extract_fields.sh "${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        shell: bash

      - name: Output Head Ref
        id: head_ref
        run: |
          echo "pr_head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Run Script to Post Release Message
        run: |
          regex="^main-branch-update-from-.*-values$"
          if [[ "${{ steps.head_ref.outputs.pr_head_ref }}" =~ $regex ]]; then
            python ./.github/scripts/post-script.py "${{ steps.head_ref.outputs.pr_head_ref }}" /tmp/description.txt /tmp/jira.txt /tmp/pr_link.txt ${{ secrets.SLACK_WEBHOOK_URL }} "${{ github.event.pull_request.html_url }}"
          else
            python ./.github/scripts/post-script.py "" /tmp/description.txt /tmp/jira.txt /tmp/pr_link.txt ${{ secrets.SLACK_WEBHOOK_URL }} "${{ github.event.pull_request.html_url }}"
          fi
