name: Rebase Pull Request

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get pull request information
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          PR_HEAD_REF=${{ github.event.issue.pull_request.head.ref }}
          PR_BASE_REF=${{ github.event.issue.pull_request.base.ref }}

          echo "Pull Request Number: $PR_NUMBER"
          echo "Pull Request Head Ref: $PR_HEAD_REF"
          echo "Pull Request Base Ref: $PR_BASE_REF"

      - name: Rebase PR branch with base branch
        continue-on-error: true
        id: rebase_pr
        run: |
          # Fetch the latest changes from the base branch
          git fetch origin ${{ github.event.issue.pull_request.base.ref }}:${{ github.event.issue.pull_request.base.ref }}

          # Checkout the pull request branch
          git checkout ${{ github.event.issue.pull_request.head.ref }}

          # Rebase the pull request branch with the base branch
          git rebase ${{ github.event.issue.pull_request.base.ref }}

          # Force push the changes back to the pull request branch
          git push origin ${{ github.event.issue.pull_request.head.ref }} --force

      - name: Add PR Comment
        if: steps.rebase_pr.outcome == 'failure'
        run: |
          # Get the PR number
          PR_NUMBER="${{ github.event.issue.number }}"

          # Add your comment using gh
          gh pr comment $PR_NUMBER --body "Your PR is not correctly rebased with ${{ github.event.issue.pull_request.base.ref }} base branch.
          ---
          **Hint:** Resolve all conflicts manually, and push it."
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
