name: Rerun the test Checklist

on:
  pull_request:
    types:
      - synchronize
    branches:
      - main
    paths:
      - charts/values.yaml

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: Add PR Comment
        run: |
          # Extract the PR number from the pull request
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # Add your comment using gh
          gh pr comment $PR_NUMBER --body "A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging environment. Mark the testing checklist below accordingly:

          ## Testing Checklist

          Changes tested on:
          - [ ] Development
          - [ ] Production
          - [ ] [MABL Tests Link] (if applicable)
          - [ ] [Successful Workflow Links] (if applicable)"
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
